"""
Spectrum Instrumentation GmbH (c) 2024

00_dds_phase_ramp_via_frequency_step.py

Card-timed phase-ramp test using a temporary DDS frequency offset.

This script keeps channel 0 and channel 1 at 300 kHz and uses a short,
timer-controlled frequency offset on channel 1 to accumulate a small phase
shift. The timing is generated by the DDS timer, not by host-side sleep calls.
"""

import spcm
from spcm import units


BASE_FREQUENCY = 300 * units.kHz
EXTERNAL_REFERENCE = 10 * units.MHz
CLOCK_TERMINATION_50OHM = False
CHANNEL_RANGE = 500 * units.mV
OUTPUT_LEVEL = 100 * units.mV
REFERENCE_CORE_INDEX = 0
TEST_CORE_INDEX = 8

# Use the exact DDS frequency grid that matches the M2p.6533 tests.
DDS_STEP_HZ = 125e6 / (2**32)
TARGET_PHASE_STEP_DEG = 0.003
DWELL_S = TARGET_PHASE_STEP_DEG / 360.0 / DDS_STEP_HZ


def print_section(title: str) -> None:
    print()
    print("=" * 80)
    print(title)
    print("=" * 80)


def initialize_pair(dds: spcm.DDS) -> tuple[float, float]:
    dds[REFERENCE_CORE_INDEX].freq(BASE_FREQUENCY)
    dds[REFERENCE_CORE_INDEX].amp(OUTPUT_LEVEL)
    dds[REFERENCE_CORE_INDEX].phase(0 * units.degrees)

    dds[TEST_CORE_INDEX].freq(BASE_FREQUENCY)
    dds[TEST_CORE_INDEX].amp(OUTPUT_LEVEL)
    dds[TEST_CORE_INDEX].phase(0 * units.degrees)

    dds.exec_now()
    dds.write_to_card()

    return (
        dds[REFERENCE_CORE_INDEX].get_freq(return_unit=units.Hz).magnitude,
        dds[TEST_CORE_INDEX].get_freq(return_unit=units.Hz).magnitude,
    )


def queue_phase_step(dds: spcm.DDS, delta_freq_hz: float, dwell_s: float, cycles: int = 1) -> float:
    # The DDS trigger source lives in the shadow register and must first be
    # transferred to the active DDS state. If the current active trigger source
    # is NONE, queued EXEC_AT_TRG commands will never advance. We therefore arm
    # the timer with an EXEC_NOW before queuing the timed states.
    dds.trg_src(spcm.SPCM_DDS_TRG_SRC_TIMER)
    dds.trg_timer(dwell_s)
    actual_dwell_s = dds.get_trg_timer()
    # dds.exec_now()
    # dds.write_to_card()
    
    dds[TEST_CORE_INDEX].freq((BASE_FREQUENCY.to(units.Hz).magnitude + delta_freq_hz) * units.Hz)
    # dds.exec_at_trg()
    dds.exec_now() # Trigger starts at exec_now() too

    dds[TEST_CORE_INDEX].freq(BASE_FREQUENCY)
    dds.exec_at_trg()

    for _ in range(cycles-1): # Repeat if cycles > 1
        dds[TEST_CORE_INDEX].freq((BASE_FREQUENCY.to(units.Hz).magnitude + delta_freq_hz) * units.Hz)
        dds.exec_at_trg()

        dds[TEST_CORE_INDEX].freq(BASE_FREQUENCY)
        dds.exec_at_trg()

    dds.write_to_card()
    return actual_dwell_s


def mute_outputs(dds: spcm.DDS) -> None:
    dds[REFERENCE_CORE_INDEX].amp(0)
    dds[TEST_CORE_INDEX].amp(0)
    dds.exec_now()
    dds.write_to_card()


card: spcm.Card

# with spcm.Card('/dev/spcm0') as card:                         # if you want to open a specific card
# with spcm.Card('TCPIP::192.168.1.10::inst0::INSTR') as card:  # if you want to open a remote card
# with spcm.Card(serial_number=12345) as card:                  # if you want to open a card by its serial number
with spcm.Card(card_type=spcm.SPCM_TYPE_AO) as card:            # if you want to open the first card of a specific type

    if card.num_channels() < 2:
        raise spcm.SpcmException(
            text="This phase-ramp test needs at least two analog output channels."
        )

    card.card_mode(spcm.SPC_REP_STD_DDS)

    channels = spcm.Channels(card, card_enable=spcm.CHANNEL0 | spcm.CHANNEL1)
    channels[0].enable(True)
    channels[1].enable(True)
    channels[0].output_load(50 * units.ohm)
    channels[1].output_load(50 * units.ohm)
    channels[0].amp(CHANNEL_RANGE)
    channels[1].amp(CHANNEL_RANGE)

    clock = spcm.Clock(card)
    clock.mode(spcm.SPC_CM_EXTREFCLOCK)
    clock.reference_clock(EXTERNAL_REFERENCE)
    clock.termination(CLOCK_TERMINATION_50OHM)
    sample_rate = clock.sample_rate(clock.max_sample_rate(return_unit=units.Hz), return_unit=units.Hz)
    clock.clock_output(False)
    card.write_setup()

    dds = spcm.DDS(card, channels=channels)
    dds.reset()
    dds.phase_behaviour(spcm.SPCM_DDS_PHASE_JUMP)
    dds.trg_src(spcm.SPCM_DDS_TRG_SRC_NONE)

    ref_freq_hz, test_freq_hz = initialize_pair(dds)

    expected_phase_deg = 360.0 * DDS_STEP_HZ * DWELL_S

    print_section("DDS Phase Ramp Via Frequency Step")
    print(f"Card: {card.product_name()}")
    print(f"Reference output: channel 0 at {BASE_FREQUENCY}")
    print(f"Test output:      channel 1 at {BASE_FREQUENCY}")
    print(f"External reference: {EXTERNAL_REFERENCE}")
    print(f"Clock mode:         external reference")
    print(f"Clock input termination: {'50 ohm' if clock.termination() else '5 kohm'}")
    print(f"Actual sample rate: {sample_rate}")
    print(f"Reference core: {REFERENCE_CORE_INDEX}")
    print(f"Test core:      {TEST_CORE_INDEX}")
    print(f"Baseline reference frequency readback: {ref_freq_hz:.12g} Hz")
    print(f"Baseline test frequency readback:      {test_freq_hz:.12g} Hz")
    print(f"DDS frequency step used: {DDS_STEP_HZ:.12g} Hz")
    print(f"Requested dwell time: {DWELL_S:.12g} s")
    print(f"Expected phase change per single cycle: {expected_phase_deg:.12g} deg")
    print()
    print("Commands:")
    print("  +   one positive phase-ramp cycle")
    print("  -   one negative phase-ramp cycle")
    print("  r+  repeated positive cycles")
    print("  r-  repeated negative cycles")
    print("  0   restore baseline immediately")
    print("  q   quit")

    card.start(spcm.M2CMD_CARD_ENABLETRIGGER, spcm.M2CMD_CARD_FORCETRIGGER)

    try:
        while True:
            command = input("\nCommand (+, -, r+, r-, 0, q): ").strip().lower()

            if command in {"q", "quit", "exit"}:
                break

            if command == "0":
                ref_freq_hz, test_freq_hz = initialize_pair(dds)
                print(
                    f"Baseline restored. Reference: {ref_freq_hz:.12g} Hz | "
                    f"Test: {test_freq_hz:.12g} Hz"
                )
                continue

            if command in {"+", "-"}:
                delta_freq_hz = DDS_STEP_HZ if command == "+" else -DDS_STEP_HZ
                actual_dwell_s = queue_phase_step(dds, delta_freq_hz, DWELL_S, cycles=1)
                sign_name = "positive" if command == "+" else "negative"
                print(
                    f"Queued one {sign_name} cycle | "
                    f"delta freq: {delta_freq_hz:.12g} Hz | "
                    f"actual dwell: {actual_dwell_s:.12g} s | "
                    f"expected phase: {360.0 * delta_freq_hz * actual_dwell_s:.12g} deg"
                )
                input("Measure now, then press Enter to continue.")
                continue

            if command in {"r+", "r-"}:
                cycle_count_text = input("Number of cycles: ").strip()
                if not cycle_count_text:
                    print("No cycle count entered.")
                    continue
                try:
                    cycle_count = int(cycle_count_text)
                except ValueError:
                    print("Cycle count must be an integer.")
                    continue
                if cycle_count <= 0:
                    print("Cycle count must be positive.")
                    continue

                delta_freq_hz = DDS_STEP_HZ if command == "r+" else -DDS_STEP_HZ
                actual_dwell_s = queue_phase_step(dds, delta_freq_hz, DWELL_S, cycles=cycle_count)
                total_expected_phase = 360.0 * delta_freq_hz * actual_dwell_s * cycle_count
                sign_name = "positive" if command == "r+" else "negative"
                print(
                    f"Queued {cycle_count} repeated {sign_name} cycles | "
                    f"delta freq: {delta_freq_hz:.12g} Hz | "
                    f"actual dwell: {actual_dwell_s:.12g} s | "
                    f"expected total phase: {total_expected_phase:.12g} deg"
                )
                input("Measure now, then press Enter to continue.")
                continue

            print("Unknown command.")
    finally:
        mute_outputs(dds)
        card.stop()
        channels[0].enable(False)
        channels[1].enable(False)
        card.write_setup()
        print("Outputs muted and analog channels disabled.")
